# Generated by Django 6.0.4 on 2026-05-01 22:32

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('customer_whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('service_type', models.CharField(choices=[('traiteur', 'Traiteur / Réception'), ('imprimerie', 'Imprimerie'), ('both', 'Traiteur + Imprimerie')], max_length=20, verbose_name='Type de service')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('reviewing', "En cours d'étude"), ('quoted', 'Devis envoyé'), ('accepted', 'Devis accepté'), ('rejected', 'Refusé'), ('completed', 'Réalisé')], default='new', max_length=20)),
                ('event_date', models.DateField(blank=True, null=True, verbose_name="Date de l'événement")),
                ('event_location', models.CharField(blank=True, max_length=300, verbose_name='Lieu')),
                ('event_description', models.TextField(blank=True, verbose_name="Description de l'événement")),
                ('catering_details', models.JSONField(blank=True, default=dict, help_text='Nombre de convives, matériel, type de menu...', verbose_name='Détails traiteur (JSON)')),
                ('print_details', models.JSONField(blank=True, default=dict, verbose_name='Détails imprimerie (JSON)')),
                ('additional_note', models.TextField(blank=True, verbose_name='Note complémentaire')),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('quote_message', models.TextField(blank=True, verbose_name='Message du devis envoyé')),
                ('quote_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande de devis',
                'verbose_name_plural': 'Demandes de devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=events.models.print_file_upload_path, validators=[events.models.validate_print_file], verbose_name='Fichier (PDF / PNG / JPG)')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size_kb', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description du fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quote_request', models.ForeignKey(blank=True, help_text='Demande de devis associée (optionnel à la création)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_files', to='events.quoterequest')),
            ],
            options={
                'verbose_name': 'Fichier imprimerie',
                'verbose_name_plural': 'Fichiers imprimerie',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
