# Generated by Django 5.2.16 on 2026-08-11 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfile',
            name='claim_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Jeton de propriété (liaison au devis)'),
        ),
    ]
