services:
  - type: web
    name: aevents-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn aevents_backend.wsgi:application --workers 2 --timeout 60 --access-logfile -
    preDeployCommand: python manage.py migrate && python manage.py create_admin
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://aeventfrontend.vercel.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://aeventfrontend.vercel.app
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ADMIN_RESET_TOKEN
        generateValue: true
      - key: ADMIN_INITIAL_PASSWORD
        generateValue: true
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USE_TLS
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
