# Generated by Django 6.0.4 on 2026-05-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='+22900000000', help_text='Numéro WhatsApp principal (format international)', max_length=20)),
                ('whatsapp_message_default', models.TextField(default="Bonjour A'Events Bénin, je souhaite avoir des informations.", help_text='Message pré-rempli WhatsApp')),
                ('address', models.TextField(default='Cotonou, Bénin', help_text='Adresse physique affichée sur le site')),
                ('email_contact', models.EmailField(blank=True, default='contact@aevents-benin.com', max_length=254)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('tagline', models.CharField(default='Prestige. Qualité. Émotion.', help_text='Accroche principale affichée sur la hero section', max_length=200)),
                ('hero_subtitle', models.TextField(default='Chaque détail compte. Chaque événement est unique.')),
                ('momo_number', models.CharField(blank=True, help_text='Numéro MTN/Moov pour paiement Academy', max_length=20)),
                ('momo_name', models.CharField(blank=True, help_text='Nom affiché pour le paiement', max_length=100)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
