# Generated by Django 6.0.4 on 2026-05-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('category', models.CharField(choices=[('patisserie', 'Pâtisserie'), ('traiteur', 'Traiteur'), ('imprimerie', 'Imprimerie'), ('academy', 'Academy'), ('coffret', 'Coffret')], default='patisserie', max_length=50)),
                ('image', models.ImageField(upload_to='galerie/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo galerie',
                'verbose_name_plural': 'Photos galerie',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(default='Cotonou, Bénin'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='momo_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='momo_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Prestige. Qualité. Émotion.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_message_default',
            field=models.TextField(default="Bonjour A'Events Bénin, je souhaite avoir des informations."),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='+22900000000', max_length=20),
        ),
    ]
