# Generated by Django 6.0.4 — Ajout du champ message pour Temoignage

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignage',
            name='message',
            field=models.TextField(default='', verbose_name='Témoignage', help_text='Le message du client'),
            preserve_default=False,
        ),
    ]
