# Generated by Django 6.0.6 on 2026-06-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_temoignage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriephoto',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Photo'),
        ),
    ]
