# Generated by Django 5.2.16 on 2026-08-16 02:42

from django.db import migrations, models

OLD = "Bonjour A'Events Bénin, je souhaite avoir des informations."
NEW = "Bonjour Arishebola Multi-service, je souhaite avoir des informations."


def update_existing(apps, schema_editor):
    SiteSettings = apps.get_model('core', 'SiteSettings')
    SiteSettings.objects.filter(whatsapp_message_default=OLD).update(whatsapp_message_default=NEW)


def revert(apps, schema_editor):
    SiteSettings = apps.get_model('core', 'SiteSettings')
    SiteSettings.objects.filter(whatsapp_message_default=NEW).update(whatsapp_message_default=OLD)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_galeriephoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_message_default',
            field=models.TextField(default='Bonjour Arishebola Multi-service, je souhaite avoir des informations.'),
        ),
        migrations.RunPython(update_existing, revert),
    ]
