# Generated by Django 6.0.4 on 2026-05-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('client_nom', models.CharField(blank=True, max_length=100)),
                ('client_wa', models.CharField(blank=True, max_length=20)),
                ('contenu', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message chat',
                'verbose_name_plural': 'Messages chat',
                'ordering': ['created_at'],
            },
        ),
    ]
