# Generated by Django 6.0.4 on 2026-05-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.CharField(choices=[('actualite', 'Actualité'), ('recette', 'Recette & Tutoriel'), ('evenement', 'Événement'), ('conseil', 'Conseil & Astuce')], default='actualite', max_length=20)),
                ('excerpt', models.TextField(blank=True, verbose_name='Résumé')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('is_published', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
