# Generated by Django 6.0.4 on 2026-05-01 22:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'accompagnement")),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix (FCFA)')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Accompagnement',
                'verbose_name_plural': 'Accompagnements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('customer_whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_note', models.TextField(blank=True, verbose_name='Note client')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('ready', 'Prête au retrait'), ('completed', 'Complétée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('pickup_date', models.DateField(verbose_name='Date de retrait souhaitée')),
                ('pickup_time', models.TimeField(verbose_name='Heure de retrait souhaitée')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix de base (FCFA)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_gallery', models.JSONField(blank=True, default=list, help_text="Liste d'URLs d'images supplémentaires")),
                ('is_box', models.BooleanField(default=False, help_text="Les coffrets ont des règles d'affichage et de composition spéciales", verbose_name='Est un coffret/Box')),
                ('box_contents', models.TextField(blank=True, help_text='Description du contenu du coffret (affiché client)')),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Quantité minimale de commande')),
                ('preparation_time_hours', models.PositiveIntegerField(default=24, help_text='Utilisé pour calculer la date de retrait minimum', verbose_name='Délai de préparation (heures)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Laisser vide = stock illimité', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_addons', models.ManyToManyField(blank=True, related_name='products', to='shop.addon', verbose_name='Accompagnements disponibles')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('selected_addons', models.JSONField(default=list, help_text='[{id, name, price}, ...] — snapshot au moment de la commande')),
                ('addons_total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
    ]
