# Generated by Django 6.0.4 on 2026-05-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_codepromo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Zone')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tarif', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Tarif (FCFA)')),
                ('delai', models.CharField(default='2-4h', max_length=50, verbose_name='Délai estimé')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'verbose_name_plural': 'Zones de livraison',
                'ordering': ['order'],
            },
        ),
    ]
