# Generated by Django 6.0.4 on 2026-05-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_zonelivraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCadeau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('acheteur_nom', models.CharField(max_length=100, verbose_name='Nom acheteur')),
                ('acheteur_wa', models.CharField(max_length=20, verbose_name='WhatsApp acheteur')),
                ('destinataire_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom destinataire')),
                ('destinataire_wa', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp destinataire')),
                ('message', models.TextField(blank=True, verbose_name='Message personnalisé')),
                ('is_used', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bon cadeau',
                'verbose_name_plural': 'Bons cadeaux',
                'ordering': ['-created_at'],
            },
        ),
    ]
