# Generated by Django 6.0.4 on 2026-05-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_boncadeau'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=100)),
                ('client_wa', models.CharField(max_length=20, unique=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('total_commandes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programme fidélité',
                'verbose_name_plural': 'Programme fidélité',
                'ordering': ['-points'],
            },
        ),
    ]
