# Generated by Django 6.0.4 on 2026-05-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_programmefidelite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parrain_nom', models.CharField(max_length=100)),
                ('parrain_wa', models.CharField(max_length=20)),
                ('filleul_nom', models.CharField(blank=True, max_length=100)),
                ('filleul_wa', models.CharField(blank=True, max_length=20)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('points_gagnes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parrainage',
                'verbose_name_plural': 'Parrainages',
            },
        ),
    ]
