# Generated by Django 6.0.4 on 2026-05-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_pack_packitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packs/'),
        ),
    ]
