# Generated by Django 5.2.16 on 2026-08-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_category_image_alter_pack_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bon_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Bon cadeau appliqué'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Réduction appliquée (FCFA)'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code promo appliqué'),
        ),
    ]
