# Generated by Django 6.0.4 on 2026-05-01 22:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la formation')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Description complète')),
                ('short_desc', models.CharField(blank=True, max_length=300, verbose_name='Accroche courte')),
                ('image', models.ImageField(blank=True, null=True, upload_to='academy/')),
                ('program_details', models.JSONField(blank=True, default=list, help_text='[{titre, description}, ...] — programme détaillé')),
                ('what_you_learn', models.JSONField(blank=True, default=list, help_text='Liste de compétences acquises')),
                ('prerequisites', models.TextField(blank=True, verbose_name='Prérequis')),
                ('instructor_name', models.CharField(blank=True, max_length=150, verbose_name='Formateur')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('all', 'Tous niveaux')], default='all', max_length=20)),
                ('location', models.CharField(default='Cotonou, Bénin', max_length=300, verbose_name='Lieu de la formation')),
                ('is_online', models.BooleanField(default=False, verbose_name='Formation en ligne')),
                ('start_datetime', models.DateTimeField(verbose_name='Date et heure de début')),
                ('end_datetime', models.DateTimeField(verbose_name='Date et heure de fin')),
                ('duration_label', models.CharField(blank=True, help_text="Ex: '2 jours', '6 heures' — libellé affiché", max_length=100)),
                ('total_seats', models.PositiveIntegerField(verbose_name='Nombre de places total')),
                ('reserved_seats', models.PositiveIntegerField(default=0, verbose_name='Places réservées')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix (FCFA)')),
                ('early_bird_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Prix Early Bird (FCFA)')),
                ('early_bird_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Fin du tarif Early Bird')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('full', 'Complète'), ('cancelled', 'Annulée'), ('past', 'Passée')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('participant_whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('participant_email', models.EmailField(blank=True, max_length=254)),
                ('participant_note', models.TextField(blank=True, verbose_name='Message / Question')),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('confirmed', 'Confirmée'), ('paid', 'Payée'), ('cancelled', 'Annulée'), ('waitlist', "Liste d'attente")], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, help_text='Ex: MTN MoMo, Moov Money, Espèces', max_length=50)),
                ('payment_ref', models.CharField(blank=True, max_length=100, verbose_name='Référence paiement')),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='academy.formation')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
                'unique_together': {('formation', 'participant_whatsapp')},
            },
        ),
    ]
