# Generated by Django 6.0.4 on 2026-05-25 07:01

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationPresentielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('domaine', models.CharField(choices=[('patisserie', 'Pâtisserie'), ('cuisine', 'Cuisine'), ('traiteur', 'Traiteur'), ('imprimerie', 'Imprimerie'), ('autre', 'Autre')], default='patisserie', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('affiche', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='affiche')),
                ('est_gratuite', models.BooleanField(default=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('has_bourses', models.BooleanField(default=False)),
                ('nb_bourses', models.PositiveIntegerField(blank=True, null=True)),
                ('age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('nb_places', models.PositiveIntegerField(blank=True, null=True)),
                ('duree', models.CharField(blank=True, max_length=100)),
                ('est_pratique', models.BooleanField(default=True)),
                ('parrain', models.CharField(blank=True, max_length=300)),
                ('sites', models.JSONField(blank=True, default=list)),
                ('date_debut_inscription', models.DateField(blank=True, null=True)),
                ('date_fin_inscription', models.DateField(blank=True, null=True)),
                ('date_tirage', models.DateField(blank=True, null=True)),
                ('date_lancement', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formation présentielle',
                'verbose_name_plural': 'Formations présentielles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierCandidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lettre_motivation', models.TextField(blank=True)),
                ('piece_identite', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='piece_identite')),
                ('photo_identite', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo_identite')),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('en_etude', 'En étude'), ('retenu', 'Retenu'), ('rejete', 'Rejeté')], default='soumis', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='academy.formationpresentielle')),
            ],
            options={
                'verbose_name': 'Dossier de candidature',
                'verbose_name_plural': 'Dossiers de candidature',
                'ordering': ['-created_at'],
            },
        ),
    ]
