# Generated by Django 5.2.16 on 2026-08-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_formationpresentielle_dossiercandidature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiercandidature',
            name='photo_identite',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dossiercandidature',
            name='piece_identite',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='formationpresentielle',
            name='affiche',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
